version: "3.4"

services:
    lotto-simulator:
        image: lottosimulator
        container_name: lottosimulator
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        networks:
            - nginx-proxy-manager_default
        ports:
            - 3973:3000
        volumes:
            - .:/app
        restart: unless-stopped
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

volumes:
    data:

networks:
    nginx-proxy-manager_default:
        external: false
        name: nginx-proxy-manager_default
